### PR TITLE
Remove bigint conditional type from UnboxDeepRequired

### LINKED ISSUE #77: Cannot find name 'bigint'
Type: Bug
Version: 2.5.4
Subject: Type Error
Environment: TypeScript 3.1.6

We are receiving the following error on build with the latest version (2.5.4).

```
ERROR in node_modules/idx/lib/idx.d.ts(52,21): error TS2304: Cannot find name 'bigint'.
node_modules/idx/lib/idx.d.ts(53,13): error TS2304: Cannot find name 'bigint'.
```

### PR DESCRIPTION
**Pull request by mohsen1**
Fixes #77

### CODE REVIEW

**Comment by malash** [comment]
LTGM

**Comment by mohsen1** [comment]
This is unnecessary with recent changes in #80
